stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - ${data.raw}
    outs:
      - ${data.processed}

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - ${data.processed}
      - params.yaml
    outs:
      - metrics.json
